---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: src/.vuepress
  label: Configuration
  create: all
  match: "**/*"
  new_doc_ext: ".json"
- type: document
  path: src/.vuepress/config.json
  label: Site Config
- type: directory
  path: docs/blog
  label: Blog Post
  create: all
  match: "**/*"
  templates:
  - blog-post
upload_dir: uploads
public_path: "/docs/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: vuepress build -d .vuepress/dist
  publish_command: vuepress build -d .vuepress/dist
  preview_output_directory: ".vuepress/dist"
  output_directory: ".vuepress/dist"
  instant_preview_command: vuepress dev -p 8080 -h 0.0.0.0
